services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: procg_node1
    working_dir: /app/server
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5434/PRO_CG?sslmode=disable
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: procg_react1
    ports:
      - "8000:80"
    depends_on:
      - backend

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: proxy_server
    ports:
      - "8080:80"
    depends_on:
      - frontend
